### ISSUE TITLE
Add support for backtracking

### ISSUE THREAD

**Issue by Michael-F-Bryan** [raphlinus/pulldown-cmark#117]
Quite a few algorithms require you to either peek at the next event or use backtracking to figure out how to parse something (e.g. we want to do `X` if the next thing is a list, but `Y` if it is normal text). 

How hard would it be to add a `set_offset()` method which can be used alongside `get_offset()` to enable backtracking and seeking backwards/forwards?

**Comment by raphlinus** [comment]
Quite unlikely. There's a _lot_ more to the state than just an offset. It's possible to use normal Rust iterators. But I think for more sophisticated logic you really want access to an AST rather than consuming a stream of events. The new_algo branch is at least partially building an AST, so I'm thinking about giving accessors to that. The official answer is to construct an AST from the event stream though.

**Comment by almereyda** [comment]
The AST conversation continues in #531

**Comment by Martin1887** [comment]
This seems out of scope, but feel free to resume the discussion if you find it useful.
