### ISSUE TITLE
enable Clone for Parser?

### ISSUE THREAD

**Issue by droundy** [raphlinus/pulldown-cmark#169]
Could we enable `Clone` for `Parser`? The use case is that I'd like in [display-as](https://crates.io/crates/display-as) to implement an optional `DisplayAs` integration with `Parser`, so users (myself, really) can have their markdown converted to HTML in the template generation.  Currently, I allocate a separate string for the markdown-generated HTML which is a bit inefficient and ugly.  The challenge is that `DisplayAs` takes a `&self`, which doesn't work with an iterator.  If I could clone the iterator, I could just mutate a copy of the object.

The other approach I could use would be to create a wrapper around a String (or `&str`) and then parse it while displaying it, but that would limit the use of `Option`s to customize the generation, so I wouldn't want to put that directly into `display-as`.

**Comment by joshleeb** [comment]
@droundy I've put up a PR that implements `Clone` for `Parser`, just to see how much work it would take. (it's not a big change)

I'm not sure what the implications of doing this are though, especially on other clients since we would need to require that the values of `Node` within `Tree` are also `Clone`.

**Comment by marcusklaas** [comment]
Hi Josh. Just wanted to check in with you on this issue.

We're currently trying to allow `FnMut` for broken link callbacks inside the parser, but it's blocked by the Clone implementation (since being able to clone a mutable reference would violate Rust's rules). Are you still using the `Parser`'s clone? I briefly check your display-as repository but didn't see any direct reference to pulldown.
