### ISSUE TITLE
treat `tel:` links similar to `mailto:` links?

### ISSUE THREAD

**Issue by marcusklaas** [raphlinus/pulldown-cmark#170]
Not 100% sure that this issue should be raised here (encountered it using https://github.com/getzola/zola, which I believe uses this crate for parsing), but here goes:

`mailto:` links like this `[email me!](mailto:joe@example.com)` get parsed to produce proper email links. Telephone links like `[call me!](tel:1-562-867-5309)` seem to generate relative links of the form `/current/rel/path/tel:1-562-867-5309` which obviously doesn't have the desired effect.

After a quick search through the code, I believe there is some special logic to detect and verify `mailto` links, but there is none such logic for phone numbers. Could that explain the behavior I'm seeing? And if so, would it make sense to add similar logic for `tel` links?

**Comment by raphlinus** [comment]
The detection of autolinks is something that changed in the commonmark spec from [0.23 to 0.24](https://spec.commonmark.org/0.24/changes.html) (search `## Autolinks`), and we haven't been doing a good job tracking those changes. Some changes would be difficult, which is why there's work on the "new_algo" branch, but this particular one would be easy, and a patch would be gratefully accepted.

**Comment by marcusklaas** [comment]
Cool, thanks for the pointers. I'll try to cook something up!
