### ISSUE TITLE
Links not compliant with CommonMark spec

### ISSUE THREAD

**Issue by critiqjo** [raphlinus/pulldown-cmark#19]
```
[link] [ref]

[ref]: http://google.com
```

Should result in "[link] " as text followed by "ref" as a link, and not a single link (as it is now).

See http://spec.commonmark.org/0.27/#example-511

Why isn't there a complete compliance test with the examples from that page itself?

**Comment by raphlinus** [comment]
I have been running the commonmark spec text, that's exactly what the "-s" option to the binary does. In the past (I think around spec 0.19 or 0.20) it successfully ran all examples. What I haven't been doing as much recently is tracking changes to the spec, and I believe this is one.

This specific issue can probably be fixed by deleting https://github.com/google/pulldown-cmark/blob/master/src/parse.rs#L1242.

There are a couple tricky implementation points that have held me back from trying to regain 100% compliance with the spec, but at some point I'll want to do that. When the spec reaches a solid 1.0 the motivation will be stronger.

**Comment by critiqjo** [comment]
Oh I see... The spec parsing is not compatible with the current formatting, so I'm not able to get a result... I will try to take a look later...

**Comment by marcusklaas** [comment]
We're compliant once again :-)
