### ISSUE TITLE
Footnote definition does not end

### ISSUE THREAD

**Issue by critiqjo** [raphlinus/pulldown-cmark#20]
``` rust
extern crate pulldown_cmark as cmark;

use cmark::{Options, Parser};

fn main() {
    for e in Parser::new_ext("Hello, [^goo]\n\n\
                              [^goo]: world.\n\n\
                              Follow [link][ref]",
                             Options::all()) {
        println!("{:?}", e);
    }
}

```

The above code outputs (footnote definition extending until the end):

```
Start(Paragraph)
Text("Hello, ")
FootnoteReference("goo")
End(Paragraph)
Start(FootnoteDefinition("goo"))
Start(Paragraph)
Text("world.")
End(Paragraph)
Start(Paragraph)
Text("Follow ")
Text("[link]")
Text("[ref]")
End(Paragraph)
End(FootnoteDefinition("goo"))
```

**Comment by raphlinus** [comment]
I sent a PR to take a look at. One question I have is, how should the following be handled:

```
a: [^b]

[^b]: * a
* b

* c

d
```

Here we have a conflict between two rules: the footnote should be closed by one blank line, but the list (which is inside the footnote) is closed by two. With the code in the PR, the list [a, b] is inside the footnote def, while c gets its own list. This seems reasonable but I want to think about whether it's truly the best behavior.

Alternatively (since the spec doesn't nail this down), we can dictate that footnotes and lists are both consistently ended by two blank lines.

**Comment by notriddle** [comment]
I (personally) don't see this as a bug. If you look in `specs/footnote.txt`, multi-paragraph footnotes are deliberately supported, and footnotes are already ended on two blank lines.

**Comment by critiqjo** [comment]
> multi-paragraph footnotes are deliberately supported

I see... I did not "expect" that (or lists) in footnotes. Generally, footnotes are a single paragraph of text.

> since the spec doesn't nail this down

If we are going to take the route of making footnotes end with a single blank line (which is probably what most people might expect, and markdown is about being intuitive, right?), then deny lists inside it (for consistency in number of blank lines). I'm against it because it will look kinda ugly if footnote definitions (containing lists) are rendered as a numeric list ([as in wikipedia](https://en.wikipedia.org/wiki/Lake_District#cite_note-2)).

**Comment by critiqjo** [comment]
When I thought about it, there's an _almost_ backwards compatible way to add back list and multi-paragraph support if there's popular demand.

Relaxing the restriction: After an empty line, in order to continue the footnote definition, indent:

```
[^b]: * a
* b

      * c

d
```

Regardless of indentations of adjacent lines following the first line of definition, the line after a blank has to be aligned with the first (non-whitespace) character of the definition body. The definition body can start in the next line too:

```
[^b]:
  * a

  * b

d
```

If it starts in the next line without any indentation, then there must be 2 blank spaces in order to terminate it, or another footnote definition.

Here's a kinda counter-intuitive restriction:

```
[^b]: * a
  * b

    c

d
```

`b` and `c` will not be in the same bullet point. `c` should be displayed as codeblock outside of footnote def. To include `c` inside `b`'s bullet, it should align with `a`.

I don't know how much increase in complexity this specification will bring about. Either way, I would suggest not to include this feature now. More the features, more the abuse!! If there's really a demand for multi-para footnotes, then we can add it with a similar spec like this.

**Comment by chriskrycho** [comment]
FWIW, the reason the spec acts the way it does is because, whatever is *most* common in writing contexts, multi-paragraph footnotes are a genuine need. (I have from time to time used them myself.) Just as importantly in many ways, pretty much all existing implementations with footnote support treat footnotes as a(n indented) block type, which allows them to have multiple paragraphs within them. So whatever is most purely "intuitive" may not be what's *best* in this case.

**Comment by ScottAbbey** [comment]
Regarding the list within footnote issue above:

> but the list (which is inside the footnote) is closed by two.

This [appears to have changed](http://spec.commonmark.org/0.27/changes.html#part-5) between CommonMark 0.26 and 0.27.

0.26:

> list items may be separated by single blank lines, but two blank lines end all containing lists

0.27:

> list items may be separated by any number of blank lines

So it is clear that the `c` list item must in all cases be a part of the list that contains the `b` list item.

It looks like this footnote spec is homegrown rather than part of the CommonMark spec.  How open is it for change?

I would not have expected list item `b` to be part of the `[^b]` footnote definition at all.  Why aren't the contents of a multi-line footnote definition required to be indented to at least the same level as the first non-whitespace character after the `[^b]:`? That seems like it would be consistent with what CommonMark does with, for example, list items.

**Comment by ScottAbbey** [comment]
Follow-up from https://github.com/google/pulldown-cmark/pull/21#issuecomment-290334612:

It looks like this footnote spec is homegrown rather than part of the CommonMark spec.  How open is it for change?

*I would not have expected list item `b` to be part of the `[^b]` footnote definition at all.*

It appears as though a footnote definition should treated as a *container block* -- all indications in this thread are that footnotes are expected to support multiple paragraphs, lists, and other blocks.

If a footnote definition is a container block, it should act very much like list items do in CommonMark.  Continuing lines in a footnote definition should be indented to the same level as the first non-whitespace character after the `[^b]:` item.  The rules to end a list item should apply to a footnote definition.

Is there an argument against treating footnotes as an additional type of container block similar to a list item?

**Comment by critiqjo** [comment]
foot[^note1], foot[^note2]

    [^note1]: text1
    [^note2]: text2

Generates:

    [
        Start(Paragraph),
        Text("foot"),
        FootnoteReference("note1"),
        Text(", foot"),
        FootnoteReference("note2"),
        End(Paragraph),
        Start(FootnoteDefinition("note1")),
        Start(Paragraph),
        Text("text1"),
        SoftBreak,
        FootnoteReference("note2"),           # note this
        Text(": text2"),
        End(Paragraph),
        End(FootnoteDefinition("note1"))
    ]

Instead of:

    [
        Start(Paragraph),
        Text("foot"),
        FootnoteReference("note1"),
        Text(", foot"),
        FootnoteReference("note2"),
        End(Paragraph),
        Start(FootnoteDefinition("note1")),
        Start(Paragraph),
        Text("text1"),
        End(Paragraph),
        End(FootnoteDefinition("note1"))
        Start(FootnoteDefinition("note2")),
        Start(Paragraph),
        Text("text2"),
        End(Paragraph),
        End(FootnoteDefinition("note2"))
    ]

Which can be generated if there is a blank line between footnote definitions. Is this intentional?

**Comment by ScottAbbey** [comment]
> Which can be generated if there is a blank line between footnote definitions. Is this intentional too?

It appears to be intentional as that is covered specifically by a test case in the footnotes.txt spec.  I would have expected your example to be two separate footnote definitions if I hadn't read that spec first.

**Comment by notriddle** [comment]
I just made it up.

**Comment by critiqjo** [comment]
After going through the spec for lists once again, and keeping the goal to maximize intuitiveness, I rewrote the spec I proposed earlier ([in-place](https://github.com/google/pulldown-cmark/issues/20#issuecomment-208147999)). Please take a look. I tried to make it consistent with the current style of specs.

**Comment by ScottAbbey** [comment]
This example:

```
[^long-footnote-name]:
  inside footnote
  * list item inside footnote
outside footnote
```

Would be all one list item due to lazy continuation rules.  The "outside footnote" text would be part of the "list item inside footnote" ([see here](http://spec.commonmark.org/dingus/?text=%3E%201.%20%3E%20Blockquote%0A%3E%20continued%20here.%0A))

Considering your second example as a list item rather than a footnote, it seems fine.  However, this version should probably all be one footnote due to laziness:

```
[^b]: text
inside footnote
```

I agree with your third example.

It seems like the one place this still differs from list items is dealing with a long footnote name.  Subsequent blocks inside a list item need to be indented as far as the first non-whitespace character after the list marker.  If the footnote name is very long, this is impractical.

I think the discussion starting with "Would it help to adopt a two-space rule?" under [5.2.1 Motivation](http://spec.commonmark.org/0.27/#motivation) in the CommonMark spec may be relevant here.

Perhaps a two-space rule can be justified by something like "The `[^` is the footnote definition indicator, so everything should be indented past that." Not sure. Seems a little messy still.

**Comment by critiqjo** [comment]
@ScottAbbey You're right, that's indeed an inconsistency. I'll update the proposal soon.

**Comment by oberien** [comment]
What's the status on this? I just ran into this problem with the following reference-list:

```md
[^foo]: foo
[bar]: bar
```

This generates the following events, which make the parser not being able to find the link definition and call the broken_link_callback:

```rust
Start(FootnoteDefinition("foo")),
Start(Paragraph),
Text("foo"),
SoftBreak,
Text("[bar]: bar"),
End(Paragraph),
End(FootnoteDefinition("foo"))
```

**Comment by chriskrycho** [comment]
Looking at the proposed spec here, and this one is probably not *quite* right:

> 3. If a sequence of blocks should be contained within a footnote definition, indent it to align with the first non-whitespace character in the definition body.
> 
> ```
> [^b]: * list item1 inside footnote
>       * list item2 inside footnote
> * list item outside footnote
> ```

The indentation rule here is unnecessarily different from the rules for other container types. Most of them allow this variation instead

```markdown
A paragraph of text to host a footnote.[^b]

[^b]: Here is a paragraph in the footnote, and then a list.

    * list item1 inside footnote
    * list item2 inside footnote

* list item outside footnote
```

This is how [pandoc renders it][p]

[p]: https://pandoc.org/try/?text=A+paragraph+of+text+to+host+a+footnote.%5B%5Eb%5D%0A%0A%5B%5Eb%5D%3A+Here+is+a+paragraph+in+the+footnote%2C+and+then+a+list.%0A%0A++++*+list+item1+inside+footnote%0A++++*+list+item2+inside+footnote%0A%0A*+list+item+outside+footnote&from=markdown&to=&standalone=0

```html
<p>A paragraph of text to host a footnote.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<ul>
<li>list item outside footnote</li>
</ul>
<section class="footnotes" role="doc-endnotes">
<hr />
<ol>
<li id="fn1" role="doc-endnote"><p>Here is a paragraph in the footnote, and then a list.</p>
<ul>
<li>list item1 inside footnote</li>
<li>list item2 inside footnote</li>
</ul>
<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></li>
</ol>
</section>
```

That is, roughly (given the limitations of GH's HTML rendering):

<blockquote>
<p>A paragraph of text to host a footnote.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<ul>
<li>list item outside footnote</li>
</ul>
<section class="footnotes" role="doc-endnotes">
<hr />
<ol>
<li id="fn1" role="doc-endnote"><p>Here is a paragraph in the footnote, and then a list.</p>
<ul>
<li>list item1 inside footnote</li>
<li>list item2 inside footnote</li>
</ul>
<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></li>
</ol>
</section>
</blockquote>

What's more, it renders the same regardless of the amount you indent within the block as long as there is no end to the contained block—for example, [with a list immediately following][p2].

[p2]: hhttps://pandoc.org/try/?text=A+paragraph+of+text+to+host+a+footnote.%5B%5Eb%5D%0A%0A%5B%5Eb%5D%3A%0A*+list+item1+inside+footnote%0A*+list+item2+inside+footnote%0A*+list+item+outside+footnote&from=markdown&to=&standalone=0

Without suggesting that Pandoc's implementation is *normative*, it's nonetheless fairly representative. There's some variation on the treatment of the `* list item outside footnote` bit in other implementations, as well as on what indentation is required. Pandoc footnotes don’t require indentation *at all* as long as there is no double-newline ending the block. Most other implementations I’m aware of *do* require indentation, of whatever size is required to start/continue a new block child in the implementation generally.

That means rule 3 should actually be something like:

> 3. If a sequence of blocks should be contained within a footnote definition, indent it as a block continuation (the same as continuing a list).
> 
> ```
> [^fn-def]:
>     * list item1 inside footnote
>     * list item2 inside footnote
> * list item outside footnote
> ```

This could/should be a bit more precise: it would be best to match up that indentation rule with the normal block continuation rules from the CommonMark spec.

**Comment by chriskrycho** [comment]
Note for folks following this thread: I am (albeit very slowly) working my way toward a solution to alllll the footnote issues over on #544. Honestly, it’ll likely be the end of the year before I have something working (at earliest!) but I really, *really* want “standard” footnotes to just work in pulldown-cmark, so I’m going to keep pushing on it, however slowly.

**Comment by ssokolow** [comment]
It also breaks this example from [GitHub's GFM docs](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#footnotes)...

```gfm
[^1]: My reference.
[^2]: To add line breaks within a footnote, prefix new lines with 2 spaces.
  This is a second line.
```

...and renders multiple footnote definitions in a group incompatible with [Prettier](https://prettier.io/), which collapses away any blank lines you manually insert between them and likely will insist that you're in the wrong if you don't bow to their decision that different Markdown dialects must have non-standard extensions.

(At least, that was their opinion when I asked for a config option to support how Doxygen draws semantic distinctions between certain synonymous Markdown constructs that Prettier currently normalizes.)

...as such, I can't currently use footnotes in any context where more than one definition is grouped together in sequence because my Prettier-on-save will induce pulldown-cmark to produce corrupted output.

**Comment by ShaunSHamilton** [comment]
This one stumped me for a long time. I really hope there will be a fix at some point.

Currently, I have to:

```markdown
[^1]: Def for 1

\

[^2]: Def for 2
```

Which would be fine, except it adds a lot of spacing in the resultant HTML
