### ISSUE TITLE
New denial of service attack!

### ISSUE THREAD

**Issue by marcusklaas** [raphlinus/pulldown-cmark#280]
Was going over the inline html scanning routines when I ran into some questionable scanning methods. In particular, parsing repetitions of `"a <![CDATA["` will scale quadratically!

Haven't tested other parsers yet. It would probably be good to test them as well and let them know when they are also vulnerable.

**Comment by marcusklaas** [comment]
md4c is vulnerable also

**Comment by marcusklaas** [comment]
and so is cmark..

**Comment by mity** [comment]
@marcusklaas Fixed in MD4C by remembering how far we have scanned for the expected HTML closer without finding it. Later attempts for re-scanning for the same closer then may fail early.

Note other raw HTML openers (e.g. HTML processing instructions or declarations) exhibited the same problem so you may check it too.

**Comment by marcusklaas** [comment]
Thanks for the pointers! Good to have the parser people looking out for eachother ^^

The `<?` and `<A` vulnerabilities I hadn't caught and by looking at the code, pulldown-cmark is vulnerable to these as well.

**Comment by oberien** [comment]
Is `a <![CDATA[` just a special case of `a <!A`? Or is it actually due to containing `<![CDATA[`?

**Comment by mity** [comment]
The specs sees them as separate because the rules for starting/ending them is different.

See https://spec.commonmark.org/0.29/#declaration versus https://spec.commonmark.org/0.29/#cdata-section.

That said, implementation make share some code, but obviously not all of it.
