### ISSUE TITLE
Footnote below unordered list wraps list item contents in paragraph elements

### ISSUE THREAD

**Issue by HanKruiger** [raphlinus/pulldown-cmark#413]
# Step to reproduce

- Have a footnote directly below an unordered list:

```markdown
Lorem ipsum.[^a]

An unordered list before the footnotes:
* Ipsum
* Lorem

[^a]: Cool.
```

# Expected output

```html
<p>Lorem ipsum.<sup class="footnote-reference"><a href="#a">1</a></sup></p>
<p>An unordered list before the footnotes:</p>
<ul>
    <li>Ipsum</li>
    <li>Lorem</li>
</ul>
<div class="footnote-definition" id="a"><sup class="footnote-definition-label">1</sup>
    <p>Cool.</p>
</div>
```

# Actual output

```html
<p>Lorem ipsum.<sup class="footnote-reference"><a href="#a">1</a></sup></p>
<p>An unordered list before the footnotes:</p>
<ul>
    <li><p>Ipsum</p></li>
    <li><p>Lorem</p></li>
    <div class="footnote-definition" id="a"><sup class="footnote-definition-label">1</sup>
        <p>Cool.</p>
    </div>
</ul>
```

I have added this (failing) test in my fork. See the comparison [here](https://github.com/HanKruiger/pulldown-cmark/compare/master...HanKruiger:add-footnote-test-after-ul), and feel free to use it or ignore it.

Cheers!

**Comment by marcusklaas** [comment]
Thanks for filing this issue! This looks like a bug to me as well, but not for the same reason. The paragraphs within the list items is a natural consequence of the list no longer being [tight](https://spec.commonmark.org/0.29/#tight) because the footnote is considered part of the list, which seems to be the underlying problem.

I would expect this output:
```html
<p>Lorem ipsum.<sup class="footnote-reference"><a href="#a">1</a></sup></p>
<p>An unordered list before the footnotes:</p>
<ul>
    <li>Ipsum</li>
    <li>Lorem</li>
</ul>
<div class="footnote-definition" id="a"><sup class="footnote-definition-label">1</sup>
    <p>Cool.</p>
</div>
```
I suspect this is an ordering issue in `parse_block`, which has proven tricky to get right when footnotes were first added to the redesign. I'll look into it.

**Comment by HanKruiger** [comment]
Oh yes, you're right. That's also the output I expected, but I didn't notice that the footnote was also inside the `<ul>`! I'll edit the post to make it clearer.

Thanks for taking a look!

**Comment by marcusklaas** [comment]
Fixed! Thanks again for filing this.
