### ISSUE TITLE
Line breaks in code blocks

### ISSUE THREAD

**Issue by dhardy** [raphlinus/pulldown-cmark#485]
Markdown's out-of-line code blocks start and end with a line-break which usually isn't considered part of the block. Example:

```
let x = 1;
let y = x + 1;
```

Pulldown-cmark's output:
```
Start(
    CodeBlock(
        Fenced(
            Borrowed(
                "",
            ),
        ),
    ),
)
Text(
    Borrowed(
        "let x = 1;\nlet y = x + 1;\n",
    ),
)
End(
    CodeBlock(
        Fenced(
            Borrowed(
                "",
            ),
        ),
    ),
)
```

That last `\n` should be stripped from the `Text` element, right? I consider it not part of the block. If I want to apply highlighting (e.g. background colour) to the code-block, that should not affect the line-break following the `Text` block.

Related: #457

**Comment by dhardy** [comment]
(Side-note: correctly handling line-breaks between elements appears to be non-trivial. [This is my current code](https://github.com/kas-gui/kas-text/pull/29/files#diff-fbbe0adaa8a509dbed681fd957851b21R77-R113) for a very limited sub-set of Markdown. Note that eventually inter-paragraph gaps will be more flexible but `\n\n` is used for now.)

**Comment by marcusklaas** [comment]
Hmmm, it's not clear to me whether the trailing newline should be included or not. Commonmark dingus seems to behave in a similar way, so I think we need fairly strong arguments to deviate.

**Comment by dhardy** [comment]
I think you need clear advice on how to handle it. If it stays, then my implementation will probably have to strip the last newline, which is annoying (but nevermind that so long as it's clear). I was rather surprised.

**Comment by BenjaminRi** [comment]
I think the spurious newline will cause more harm than good for library users. People who want the extra newline could easily emit an extra one in `Event::End(Tag::CodeBlock(_))`.

Unfortunately, the [CommonMark spec](https://spec.commonmark.org/0.29/#indented-code-blocks) is clear about emitting this line break.

All the examples, like for example example 89, display a spurious newline at the end of the CodeBlock:

````
```
<
 >
```
````

transforms to:

```
<pre><code>&lt;
 &gt;
</code></pre>
```

The only exception is the empty code block (example 100):

````
```
```
````

which transforms to:

```
<pre><code></code></pre>
```

Interestingly, this means that it's impossible to make a non-empty code block containing a one-liner without newline.

Removing the newline would violate the spec. So, while the behaviour is essentially broken, it is broken by design, and unfortunately the spec must be adhered to if we want any compatibility in the ecosystem.

**Comment by dhardy** [comment]
@BenjaminRi given that the CommonMark spec is defined in terms of HTML, compliance with that is still possible by pushing the new-line in the HTML serializer (for `Event::End(Tag::CodeBlock(_))`, only when the prior event was `Event::Text` and not empty), weakening your argument.

Further to this point, line-breaks in HTML source don't necessarily correspond to line-breaks in the output: it appears to make no difference in rendered HTML whether the last line of content is followed by a line-break inside `<code>...</code>`.

Adding the above rule to the HTML serializer would be annoying complexity I know, but handling line-breaks for Unicode output is also [annoyingly complex](https://github.com/kas-gui/kas-text/blob/master/src/format/markdown.rs#L256). (In fact, even the semantics of line-breaks in Unicode are complex, [as @raphlinus well knows](https://crates.io/crates/xi-unicode).)

**Summary:** `pulldown-cmark`'s output is not HTML, so the CommonMark spec does not apply (directly). An additional layer of specification is needed, and there is still some room for manoeuvre in what that spec says.

**Comment by Martin1887** [comment]
This seems not a real issue to me. Feel free to resume the discussion if you find it useful.
