### ISSUE TITLE
BrokenLinkCallback: Ownership and Send + Sync?

### ISSUE THREAD

**Issue by edward-shen** [raphlinus/pulldown-cmark#508]
I was looking around the codebase and noticed that Rust has determined that `Parser` was `!Send` and `!Sync`. I thought it was odd because from a very high level perspective, it seems reasonable to expect us to be able to send a parser object between threads without difficulty--synchronous access maybe not so much (I can't really imagine a use case for when a client might want to have a parser be access from multiple threads at the same time) but `Send` implies `Sync` so ¯\\\_(ツ)\_/¯.

It looks like the primary problem is that the type `BrokenLinkCallback` isn't Send nor Sync because we don't require the trait object to be send or sync:

```rust
pub type BrokenLinkCallback<'a> =
    Option<&'a mut dyn FnMut(BrokenLink) -> Option<(CowStr<'a>, CowStr<'a>)>>;
```

A quick fix is to just require the trait object reference to be Send + Sync:

```rust
pub type BrokenLinkCallback<'a> =
    Option<&'a mut (dyn Send + Sync + FnMut(BrokenLink) -> Option<(CowStr<'a>, CowStr<'a>)>)>;
```

but since `BrokenLinkCallback` is part of the public API, this would be a breaking change as it restricts what functions are accepted.

As a [refresher on Closure auto-impl rules][refresher]:
 - A closure is Sync if all captured variables are Sync.
 - A closure is Send if all variables captured by non-unique immutable reference are Sync, and all values captured by unique immutable or mutable reference, copy, or move are Send.

I might be wrong, but I don't think adding this requirement would be too difficult on users. I would expect most use cases to already be `Send` and `Sync` (our tests need no modification, for example), and I believe the current definition `&mut dyn FnMut` already forces some sort of Send/Sync primitive around the Parser itself, if they need to do so.

On that note, is there a particular reason why we accept a `&mut` to a callback, instead of an owned instance we `Box` instead or have `Parser` be generic over the trait?

[refresher]: https://doc.rust-lang.org/reference/types/closure.html

**Comment by marcusklaas** [comment]
It would have been good to have this, but I am afraid that this would be too restrictive. We could no longer capture any mutable references, since they aren't `Sync`. This would effectively limit the callbacks to `Fn(BrokenLink) -> ...`.

> On that note, is there a particular reason why we accept a `&mut` to a callback, instead of an owned instance we `Box` instead or have `Parser` be generic over the trait?

We could have gone with either alternative here, and the trade-offs are a toss up. Boxing obviously has an allocation cost, and using static dispatch *could* be faster. However, there are costs for static dispatch too. There's increased compilation time, increased binary size (when using different callbacks) and most importantly the possible inlining of very cold code. That last point is also the reason why we didn't sweat too much over this decision: the callback should be called very infrequently and hence the design shouldn't impact performance very much at all.

**Comment by mattwidmann** [comment]
I appreciate the thought that's gone into the design of pulldown-cmark's API, in particular around the callback as it sounds like a difficult set of tradeoffs to deal with. But I do have a different perspective on one point:

> the callback should be called very infrequently and hence the design shouldn't impact performance very much at all.

This is not necessarily a safe assumption to make for all users of the library. For instance, in a wiki system I've built, all links are written as `[Thing]`, and the broken link callback does the work to both resolve that link (as `/pages/thing/`, for instance), and append the current page to a list of "backlinks" for the "Thing" page (requiring a mutable reference to a hash table). The broken link callback is definitely on the typical path for the program I've written.
