### ISSUE TITLE
specify LinkType in broken_link_callback

### ISSUE THREAD

**Issue by arnaudgolfouse** [raphlinus/pulldown-cmark#516]
Hello !
I am trying to build something that takes markdown and output markdown, while resolving some broken links.
This is going pretty well, except that `Parser::new_with_broken_link_callback` only resolves broken links to `LinkType::Reference`, where I would like to have some `LinkType::Shortcut`.

I guess this isn't possible with the current design however, and the signature of `new_with_broken_link_callback` would need to be changed to something like:
```rust
pub fn new_with_broken_link_callback(
    text: &'a str,
    options: Options,
    broken_link_callback: Option<&'a mut dyn FnMut(BrokenLink<'_>) -> Option<(LinkType, CowStr<'a>, CowStr<'a>)>>
) -> Parser<'a>
```

So, hu, I guess this is a breaking change 😅 But it would be nice to see this if possible 🙂

**Comment by marcusklaas** [comment]
Hi Arnaud. If I understand your intention correctly, this should be feasible in the current design.

Links that have been 'restored' using the broken link callback are assigned a special 'Unknown..' link type. If you want to change link types, instead of assigning these in the broken link callback (which would be a breaking change indeed), you can achieve this using an event transformation.

This is untested code, but it could roughly look like this:
```rust
Parser::new_with_broken_link_callback(markdown_input, Options::empty(), callback)
    .map(|event| match event {
        // matches broken reference links that have been restored by the callback
        // and replaces them by shortcut variants
        Event::Link(LinkType::ReferenceUnknown, dest, title) => Event::Link(LinkType::ShortCut, dest, title),
        _ => event,
    })
```

Would that accomplish what you set out to do?

**Comment by arnaudgolfouse** [comment]
Oh I thought it assigned them to `Reference`, but you are right ! Then this is exactly what I want, thank you !
For reference, it seems the assigned link type was `ShortcutUnknown`.
