### ISSUE TITLE
Construct AST?

### ISSUE THREAD

**Issue by vedantroy** [raphlinus/pulldown-cmark#531]
The README says "and quite straightforward to construct an AST". I've been finding it rather difficult though to turn the events into a recursive enum data structure.

Something very roughly like:

```rust
enum Block {
    Paragraph(Vec<Inline>)
    Header((usize, Vec<Inline>)) // level, content
    Blockquote(Vec<Block>) // blockquotes can container other blocks
}

enum Inline {
   Text(String),
   Bold(String)
  // ...
}
```
the issue is, when I receive an event through the iterator I need to push a child to whatever the current node is (if the current node even supports having child of the given type, a `Blockquote` might  support a `Fenced` child but a `Header` will not). This seems complicated. Not sure if I need to use traits/if there is a better way?

One way to solve this problem would be to just write JSON directly from the events, but it feels better to create a proper Rust struct first & then use Serde on that?

**Comment by marcusklaas** [comment]
Hi Vedant,

First of all I am so sorry for getting back to you with such a great delay. You've probably moved on from this topic long ago. Still, I'd like to answer you question.

I think your approach is generally right. It's what I would try as well. I am not sure you need to worry about this, though:
> the issue is, when I receive an event through the iterator I need to push a child to whatever the current node is (if the current node even supports having child of the given type, a `Blockquote` might  support a `Fenced` child but a `Header` will not).

You could probably rely on pulldown only generating proper children. If you found pulldown producing a `Fenced` event inside a `Header`, that would be a fault on our part, and learning that would be extremely valuable :-)

The only other tip I can give you is to keep a list of 'ancestors', that is, a path back to the root node. Every time you receive an `End`, you need to take a step back towards the root (the node's parent). Since the AST nodes themselves only store information about their children, you'd need to keep this information in a separate stack whilst you're constructing the AST.

I hope this helps you, or perhaps any others with similar questions. If we can be of further assistance, please re-open the issue. I aim to be more responsive in the future!
