### ISSUE TITLE
Strikethrough does not work midword like on GitHub

### ISSUE THREAD

**Issue by not-my-profile** [raphlinus/pulldown-cmark#532]
GitHub renders `~~foo~~bar` as ~~foo~~bar and `foo~~bar~~` as foo~~bar~~.

pulldown-cmark however doesn't recognize both strikethroughs:

```
$ echo '~~foo~~bar' | cargo run  -- -S
<p>~~foo~~bar</p>
$ echo 'foo~~bar~~' | cargo run  -- -S
<p>foo~~bar~~</p>
```

Unfortunately the [GFM spec doesn't say much about strikethroughs](https://github.github.com/gfm/#strikethrough-extension-) (see  github/cmark-gfm#74), but we could of course still be consistent with the established GitHub rendering.

**Comment by marcusklaas** [comment]
Hi! Thanks for reporting this, and my apologies for only getting back to you now.

I think we certainly would like to be consistent with GitHub where we can, but to me it's not entirely clear whether strikethrough behavior is merely underspecified, or that the GitHub implementation of the spec is incorrect, especially since the behavior is not consistent with that of other text modifiers.

As long as we are consistent with the latest spec, I am very open to persuasion on this issue.

**Comment by SilverBut** [comment]
Considering the strikethrough discussion in the standard [have not made much process for almost 10 years](https://talk.commonmark.org/t/strikeout-threw-out-strikethrough-strikes-out-throughout/820/46) and the GFM is surely popular, maybe we should consider following GFM by making strikethrough works in midword.

Also, for CJK and some other languages, words are not split by space. Instead, characters in those languages will group into words by their meaning. Japanese wikipedia gave a [good example](https://ja.wikipedia.org/wiki/Help:%E3%83%9A%E3%83%BC%E3%82%B8%E3%81%AE%E7%B7%A8%E9%9B%86#%E5%8F%96%E3%82%8A%E6%B6%88%E3%81%97%E7%B7%9A%E3%83%BB%E4%B8%8B%E7%B7%9A):

<img width="783" alt="image" src="https://github.com/raphlinus/pulldown-cmark/assets/6560655/45a478f9-9191-432d-896c-bf689116befb">

(Translate: Texts are ~~partially removed~~ _and new text inserted_ like this)

Thus, making strikethrough works in midword is useful for CJK users, and not affecting other people meanwhile.

cc @marcusklaas if you are still following this issue

**Comment by Martin1887** [comment]
Good point, I will work on this soon.
