### ISSUE TITLE
Any interest in supporting wiki-style links?

### ISSUE THREAD

**Issue by ryanisaacg** [raphlinus/pulldown-cmark#550]
For context: `[[wiki-style-link-target]]`, `[[wiki-style-link-target|Here's the link label!]]`

I know they're very nonstandard, but some markdown-wiki apps like [Obsidian](https://obsidian.md/) use them (see [the Obsidian local link docs](https://help.obsidian.md/How+to/Internal+link)).

If there's interest in this being part of pulldown-cmark proper I can try putting together a patch; if not, I'll just work on it as a minor fork.

**Comment by raphlinus** [comment]
My personal feeling is that it's pretty far out of scope. We get good mileage from pulldown-cmark being very focused on CommonMark and not trying to be a general purpose markup parser. Also, I think philosophically we're trying to support convergence on a standard, rather than the (admittedly Wiki-like) fragmentation of syntax.

Doing it as a fork is fine! I think the code is stable to the point that the burden of maintaining a fork is not huge.
