### ISSUE TITLE
Front Matter Support

### ISSUE THREAD

**Issue by equt** [raphlinus/pulldown-cmark#580]
Would it be great to have support for front matter support, or is there any reason it's not implemented? Many popular dialects support this, e.g., GitHub renders it as a table, and it's much more doable (in my opinion) than adding support for math.

**Comment by yankeeinlondon** [comment]
I think frontmatter is very important, though I guess one could extract that quite easily before sending to the parser and then have that be a separate concern

**Comment by ecumene** [comment]
For those who are interested, here's a little extractor I made:

```rust
#[derive(Deserialize, Serialize)]
pub struct Markdown<T> {
    pub meta: T,
    pub content_markdown: String,
    pub content_html: String,
}

const FRONTMATTER_DELIMITER: &str = "---";

pub fn parse_frontmatter<'de, T>(post: &'de str) -> (T, String)
where
    T: serde::Deserialize<'de>,
{
    let first_line = post.lines().next();
    let mut sections = post.split(FRONTMATTER_DELIMITER);
    if let Some(line) = first_line {
        if FRONTMATTER_DELIMITER == line {
            let frontmatter = sections.nth(1).expect("No frontmatter");
            let content = sections.next().expect("No content");
            return (
                toml::from_str(frontmatter).expect("Couldn't serialize frontmatter."),
                content.to_string(),
            );
        }
    }
    panic!("No frontmatter.");
}

pub fn parse<'de, T>(source: &'de str) -> Result<Markdown<T>, toml::de::Error>
where
    T: serde::Deserialize<'de>,
{
    let (meta, rest): (T, String) = parse_frontmatter(source);
    let html = custom_markdown_to_html(rest);

    Ok(Markdown {
        meta,
        content_html: html,
        content_markdown: String::from(source),
    })
}
```

**Comment by o-az** [comment]
@ecumene do you have an example on how we can use it with `pulldown-cmark` by chance?

**Comment by ecumene** [comment]
> @ecumene do you have an example on how we can use it with `pulldown-cmark` by chance?

[https://github.com/ecumene/ecumene/blob/master/src/template.rs#L45](here's a more complete example)

**Comment by yankeeinlondon** [comment]
Note, i'm using the `gray_matter` crate now for frontmatter and it works well. I suggest we keep this repo focused on just parsing the markdown-to-html and let people who want/need frontmatter to "pre-parse" the frontmatter separately.

**Comment by jaythomas** [comment]
Am I missing a point of this issue? The frontmatter and markdown are parsed independently. Frontmatter isn't the markdown parser's concern.

https://github.com/noisefloors/matter

```rust
use pulldown_cmark::{Parser, html, Options};
use matter::matter;

...

let input = std::fs::read_to_string("./path/to/content.md").unwrap();
if let Some((matter, markdown)) = matter(&input) {
    let mut options = Options::empty();
    let parser = Parser::new_ext(&markdown, options);
    // Save some re-allocations during parsing with a large-enough pre-allocation
    let mut html_output = String::with_capacity(4000);
    html::push_html(&mut html_output, parser);
}
```

I see there is also an adjacent crate to this one [pulldown-cmark-frontmatter](https://github.com/khonsulabs/pulldown-cmark-frontmatter) but it looks like it enforces a non-standard frontmatter format and doesn't look like the api saves much if any boilerplate.

**Comment by yankeeinlondon** [comment]
@jaythomas I think it's just a "nice-to-have" for as the meta-data is very likely packaged along with the content (as well as being used to manipulate the content). 

Further, even if you're disregarding the meta-data in the content you'd need to be sure that the two parts are separated before putting file content through pull-cmark but that said, any graymatter crate (or code) that you use will need to do this too so you could simply rely on it's functionality and then just pass the content to pulldown-cmark.

I suspect to keep the footprint down to size this issue is probably best closed.

**Comment by Martin1887** [comment]
I think that metadata blocks should be at least ignored, since for instance a comment in a metadata block is parsed as a heading in the Markdown document. Similarly, a metadata block that ends with ' ---'  is parsed as a SETEXT H2 heading.

I'm considering here metadata blocks in any part of the document, as Pandoc does, so all (or almost all) libraries parsing frontmatters will not remove them and therefore they are not a solution.

 Removing manually the metadata blocks would neither be a good solution if ranges are needed. For example, I'm using ranges to replace chunks because there is no a Markdown renderer in this crate that acts over the modified events.

**Comment by jaythomas** [comment]
> I think that metadata blocks should be at least ignored

Perhaps as an option, but in my use case I shared above the frontmatter crate handles splitting the markdown and frontmatter apart, then only the subset of data that is markdown is passed over to pulldown-cmark. Think of the document as a superset and only a subset of it is markdown, therefore only the markdown subset is the concern of the markdown parser.

**Comment by Martin1887** [comment]
I understand your point, but doing that would be very difficult to modify a Markdown document with metadata blocks, since the ranges reported from pulldown-cmark would not match the ranges of the 'super-document'.

When using a Markdown parser you are not always the final processor, and you may want to modify some parts as a preprocessor without losing anything else.

Therefore, I think the best solution is handling metadata blocks as a special type of comment when a new flag is enabled.
