### ISSUE TITLE
`|` in tables breaks the layout

### ISSUE THREAD

**Issue by treeman** [raphlinus/pulldown-cmark#590]
This text:

```
| One   | Two
| ---   | ---
| `|`   | 2
```

Doesn't output what I expect (it's broken on GitHub too):

```
<table><thead><tr><th>One</th><th>Two</th></tr></thead><tbody>
<tr><td>`</td><td>`</td></tr>
</tbody></table>
```

| One   | Two
| ---   | ---
| `|`   | 2

But other characters work:

```
| One   | Two
| ---   | ---
| `x`   | 2
```

| One   | Two
| ---   | ---
| `x`   | 2

Code tags also doesn't work (and not on GitHub):

```
| One   | Two
| ---   | ---
| <code>|</code>   | 2
```

| One   | Two
| ---   | ---
| <code>|</code>   | 2

Escaping makes the table look ok, but pulldown includes the `\` in the output `<code>\|</code>` while it works on GitHub:

```
| One   | Two
| ---   | ---
| `\|`   | 2
```

| One   | Two
| ---   | ---
| `\|`   | 2

**Comment by marcusklaas** [comment]
Yup, it's a known issue. I don't recall the details, but I remember that none of the solutions were particularly compelling, which is why there hasn't been much progress on this topic.

I'll close this since it's technically a duplicate issue, but know that it is a problem we acknowledge and hope to resolve!

**Comment by ehuss** [comment]
For the record, #356 is the duplicate, and it contains some workarounds.
