### ISSUE TITLE
Why is `Tag::Heading()` using `&'a str` instead of `CowStr<'a>` like everything else?

### ISSUE THREAD

**Issue by lenscas** [raphlinus/pulldown-cmark#607]
For one of my projects it would be nice if I could get rid of the lifetime at the cost of allocating while transforming the markdown through `Parser::flat_map`. This is pretty much possible as most types/variants that have a lifetime are a `CowStr<'a>` which can easily be turned into a `CowStr<'static>`. However, the variant `Tag::Heading()` has a `Option<&'a str>` and a `Vec<&'a str>` which makes this trick not work for this.

Is there a workaround that I am missing? And is there a specific reason why this one doesn't use `CowStr<'a>` and instead uses `&'a str`'s directly?

**Comment by marcusklaas** [comment]
Ah, I think I understand your goal and how you're trying to achieve this. It would work, but indeed the heading tag will give you trouble. The reason these are string slices instead of `CowStr`s is that we're never allocating for them. Using slices instead of `CowStr`s is slightly faster, and it communicates this guarantee to the user. Usually such guarantees can be helpful, but it appears in this case it is not. I am thinking of two things you could try to work around this problem:

1. the second and third values in the heading tag are for custom ids and classes. This is a fairly niche feature that you may not want to use. So you could just return a new tag with those values replaced by `""` and `Vec::new()` (with strings slices being `'static`).
2. create new types replacing `Event` and `Tag` which are identical to the ones that pulldown uses, but with either the `&'a str` types dropped as above, or replaced by `CowStr`s. Then, you can map the events coming in to your ones, which won't have non-static lifetimes. You could even replace `CowStr`s by simple `String`s, as most your strings will be allocated.

Hope either one of these work for you.

**Comment by lenscas** [comment]
I needed it for https://github.com/lenscas/tealr_doc_gen/commit/89ab7959c453c9daaa22ad830d223062697feabb

Technically, I could keep the lifetime exposed in the types but that can quickly become complicated with lua and the macro I made doesn't support that as a result.

For now I have found a solution by just first doing the entire transformation and then going back to the types that pulldown-cmark uses in a separate iterator chain. It introduces more overhead than doing it all at once but on the flip side also gives me a good place to handle errors that come from lua so it isn't all bad.



Maybe document why headings don't use `CowStr<'a>` while the other fields do? As right now it looks more like an oversight/mistake than something that is intended to be this way due to everything else using `CowStr<'a>`

**Comment by SergioBenitez** [comment]
See https://github.com/raphlinus/pulldown-cmark/pull/614 which resolves this and can be used a basis to measure the performance impact, of any, of the change.

**Comment by HJfod** [comment]
If possible, I would like to vouch for merging #614 and changing the headings from `&'a str` to `CowStr<'a>`, if it doesn't have too much of a performance drawback. I am currently trying to implement automatic Github-style heading links, and for that I need to be able to dynamically change the ID fragment passed in `Tag::Heading`, which isn't easily possible with the current system. The alternative of consuming the whole heading and returning a self-made `Event::Html` isn't very appealing either, as plenty of the headings I'm working with contain non-text elements.

**Comment by lenscas** [comment]
I would also like to see #614 merged. It on its own probably doesn't _quite_ allow me to not have to iterate the entire thing first, as for me the modifications can fail but it would be a step into that direction.

**Comment by Martin1887** [comment]
I will check #614 relatively soon.

**Comment by Martin1887** [comment]
This has been fixed by #614.
