### ISSUE TITLE
Is the pulldown-cmark project paused/abandoned/unmaintained?

### ISSUE THREAD

**Issue by joelparkerhenderson** [raphlinus/pulldown-cmark#610]
Hi, does anyone here know if this project is paused, or abandoned, or unmaintained, etc.?

I'm asking because I see numerous open issues that are open for a long time, including pull requests that have code that looks good, yet no recent work other than version bumps, and no notable responses from maintainers to the issues or PRs.

If anyone here is able to advise, or potentially merge some of the pending PRs, that would be very helpful. Thanks!

**Comment by marcusklaas** [comment]
Hi. The project is not being actively developed any more, but that's mostly because it is considered mostly stable and feature complete (by me, anyway).

There are of course plenty of things to work on still, but I haven't had the inspiration to pick them up recently. I do try to address the most pressing issues. Of course it must be frustrating for people making PRs and issues, and I acknowledge that. I hope to get back to these relatively soon. And I'm also open to new people picking up more responsibilities for the project.

**Comment by Martin1887** [comment]
Hello.

The project seems actually unmaintained. My projects need the feature implemented in #638 and the one I'm working on that solves #580. I could work on merging them and review other pull requests and issues if I became a collaborator, but if this does not happen and my pull requests are not merged, I will have to create a new crate from my fork.


Regards,

**Comment by raphlinus** [comment]
I think we are probably in the market for a new maintainer. I'd be happy to talk about what's involved, either through a video call or possibly Linebender office hours tomorrow if you're available for those.

**Comment by Martin1887** [comment]
I will be available for a video call (in Jitsi Meet?) tomorrow from 11:00 GMT to 15:00 GMT and from 18:00 GMT to 21:00 GMT.

**Comment by raphlinus** [comment]
Sure, how about 1600 UTC, which is right after linebender office hours? Any of the major chat services works for me, you can send email with your contact info.

**Comment by Martin1887** [comment]
Perfect, this is the link for the meeting:

https://moderated.jitsi.net/ae215444bdcf4189bbd7cc84ff8613ae39fefde617c94eba8679e8b79d6a1609

Please confirm that you have received the e-mail and the link works for you.

Best Regards,

-------- Mensaje original --------

**Comment by Martin1887** [comment]
I have joined as maintainer, so the issue can be closed. @marcusklaas is unfortunately not available to keep working on this.
