### ISSUE TITLE
How to get all markdown under a section?

### ISSUE THREAD

**Issue by jorgecarleitao** [raphlinus/pulldown-cmark#626]
Hi. Beautiful library :)

Consider the markdown

```
# Section 1
This is some markdown
* a 
* b
```

I am trying to get the string

```
This is some markdown
* a 
* b
```

is there a way to do it?

From `Parser().iter()`, I can identify when the header `# Section 1` ends and thus identify the events of relevance. However, I am not able to reconstruct the markdown from the events (at least not without writing a complete "MarkdownWriter" like "HtmlWriter"). Is there a mechanism to do this? 

An alternative would be to get the span of the text in the original markdown file, but I do not see how to get the "line, column" / "bytes from start" from the events.

Any help would be appreciated.

**Comment by ehuss** [comment]
I would suggest using [`into_offset_iter`](https://docs.rs/pulldown-cmark/latest/pulldown_cmark/struct.Parser.html#method.into_offset_iter) to get the Range of where the event is in the original text.

There is [`pulldown-cmark-to-cmark`](https://crates.io/crates/pulldown-cmark-to-cmark) to convert back to text, but I generally don't recommend it, since it can sometimes not convert back completely.
