### ISSUE TITLE
[Question] Modifying a link: Start or End?

### ISSUE THREAD

**Issue by Arteneko** [raphlinus/pulldown-cmark#710]
Hi! In a website tool i'm writing, i'm facing a case where every link pointing to another file within this website may have to be changed (e.g. changing the extension from `.md` to `.html`).

From what i see, i may be able to do so using the Parser's iterator map capability, but since both `Event::Start` and `Event::End` exposes a Tag (which may contain said URL), i'm wondering about where i should intervene.

Would it be better to mutate the value on start or end?

Edit: Diving into the html renderer's source code to see how it's being handled, it becomes a bit clearer.
Though now it's letting me wonder how i could efficiently extract e.g. a heading's text content since, from my understanding, the text content will be typed as `Event::Text` and not in `Event::Start(Tag::Heading)` nor `Event::End(Tag::Heading)`.

**Comment by Martin1887** [comment]
Hello, it may seem a bit counter-intuitive, but tags make reference exclusively to the things that in HTML go between `<` and `>` (`<h1>` and `</h1>` for H1s for instance), and everything in between is the body of the tag.

Therefore, to do something like you want you have to match start and end tags and text events and track the status of the parser with additional variables. It sounds complicated but it is actually easy, here a small example:

```rust
    let mut parsing_heading = false;
    for (event, range) in parser {
        match event {
            Start(tag) => {
                if let Tag::Heading(_level, _id, _classes) = tag {
                    parsing_heading = true;
                }
            }
            End(tag) => {
                if let Tag::Heading(_level, _id, _classes) = tag {
                    parsing_heading = false;
                }
            }
            Text(text) => {
                if parsing_heading {
                    println!("{}", text);
                }
            }
            _ => {}
        }
    }
```

Take into account that an arbitrary number of text events can be between the start and end tags due to the manner of parsing of the incremental parser, this is the most counter-intuitive and error-prone feature of the parser, and a text events merger was recently added to address it.
