### ISSUE TITLE
& is escaped to `&amp;`, but is perfectly valid to be in a href tag

### ISSUE THREAD

**Issue by dvc94ch** [raphlinus/pulldown-cmark#800]
trying to understand why it's being escaped and if there is a way to disable it.

**Comment by Martin1887** [comment]
I thinks this solves your question, basically the ampersand is used to encode other characters: https://stackoverflow.com/questions/9084237/what-is-amp-used-for

**Comment by dvc94ch** [comment]
Not really. That just explains how html escapes work. The problem isn't with the html rendering. It's that you're screwing the rendering

**Comment by dvc94ch** [comment]
Taking a valid url and mangling it doesn't seem right.

**Comment by Martin1887** [comment]
Sorry, but I don't get you. The scaping is only invoked by the HTML renderer, and it is needed to have a correct HTML because, as the link previously mentioned says, an URL like 'https://domain.xyz/foo&bar' is incorrect as HTML, and it should be 'https://domain.xyz/foo&amp;bar', which is pulldown-cmark HTML renderer does.
